/**
 * Model Schemas - Zod Validation (tRPC Input/Output)
 *
 * Re-exports and extends schemas generated by Drizzle ORM.
 * Uses schemas from @/server/db/schemas for consistency.
 *
 * @module server/api/routers/admin/model/model.schemas
 */

import { z } from "zod";
import {
  modelInsertSchema,
  modelUpdateSchema,
} from "@/server/db/schemas/model.schema";
import {
  modelCostBreakdownInsertSchema,
  modelCostBreakdownUpdateSchema,
} from "@/server/db/schemas/model-cost-breakdown.schema";

// ============================================================================
// CONSTANTS
// ============================================================================

const MAX_PAGE_LIMIT = 100;
const DEFAULT_PAGE_LIMIT = 10;

// ============================================================================
// INPUT SCHEMAS (tRPC procedures)
// ============================================================================

/**
 * List models input schema
 */
export const listModelsInput = z.object({
  page: z.number().int().positive().default(1),
  limit: z
    .number()
    .int()
    .positive()
    .max(MAX_PAGE_LIMIT)
    .default(DEFAULT_PAGE_LIMIT),
  search: z.string().optional(),
  status: z.enum(["all", "draft", "published"]).default("all"),
  profileSupplierId: z.uuid().optional(),
  sortBy: z
    .enum(["name", "basePrice", "createdAt", "updatedAt"])
    .default("createdAt"),
  sortOrder: z.enum(["asc", "desc"]).default("desc"),
});

/**
 * Get model by ID input schema
 */
export const getModelByIdInput = z.object({
  id: z.uuid(),
});

/**
 * Create model input schema - extends Drizzle insert schema
 */
export const createModelInput = modelInsertSchema
  .pick({
    name: true,
    profileSupplierId: true,
    basePrice: true,
    costPerMmWidth: true,
    costPerMmHeight: true,
    compatibleGlassTypeIds: true,
    status: true,
  })
  .extend({
    compatibleGlassTypeIds: z.array(z.string()).default([]),
    status: z.enum(["draft", "published"]).default("draft"),
  });

/**
 * Update model input schema - extends Drizzle update schema
 */
export const updateModelInput = z.object({
  id: z.uuid(),
  data: modelUpdateSchema,
});

/**
 * Delete model input schema
 */
export const deleteModelInput = z.object({
  id: z.uuid(),
});

/**
 * Add cost breakdown input schema - extends Drizzle insert schema
 */
export const addCostBreakdownInput = modelCostBreakdownInsertSchema.pick({
  modelId: true,
  component: true,
  costType: true,
  unitCost: true,
});

/**
 * Update cost breakdown input schema
 */
export const updateCostBreakdownInput = z.object({
  id: z.uuid(),
  data: modelCostBreakdownUpdateSchema,
});

/**
 * Delete cost breakdown input schema
 */
export const deleteCostBreakdownInput = z.object({
  id: z.uuid(),
});

// ============================================================================
// OUTPUT SCHEMAS (tRPC procedures response types)
// ============================================================================

/**
 * Model output schema - raw database format (strings for decimals)
 * Matches exactly what Drizzle returns from the database
 */
export const modelOutput = z.object({
  id: z.string(),
  name: z.string(),
  imageUrl: z.string(),
  status: z.enum(["draft", "published"]),
  minWidthMm: z.string(),
  maxWidthMm: z.string(),
  minHeightMm: z.string(),
  maxHeightMm: z.string(),
  basePrice: z.string(),
  costPerMmWidth: z.string(),
  costPerMmHeight: z.string(),
  accessoryPrice: z.string().nullable(),
  glassDiscountWidthMm: z.string(),
  glassDiscountHeightMm: z.string(),
  compatibleGlassTypeIds: z.array(z.string()),
  profitMarginPercentage: z.string().nullable(),
  lastCostReviewDate: z.date().nullable(),
  costNotes: z.string().nullable(),
  profileSupplierId: z.string().nullable(),
  createdAt: z.date(),
  updatedAt: z.date(),
  profileSupplier: z
    .object({
      id: z.string(),
      name: z.string(),
      materialType: z.string(),
    })
    .nullable(),
});

/**
 * Model detail output schema (with relations)
 */
export const modelDetailOutput = modelOutput.extend({
  costBreakdown: z.array(
    z.object({
      id: z.string(),
      modelId: z.string(),
      component: z.string(),
      costType: z.enum(["fixed", "per_mm_width", "per_mm_height", "per_sqm"]),
      unitCost: z.string(),
      notes: z.string().nullable(),
      createdAt: z.date(),
      updatedAt: z.date(),
    })
  ),
  priceHistory: z.array(
    z.object({
      id: z.string(),
      modelId: z.string(),
      basePrice: z.string(),
      costPerMmWidth: z.string(),
      costPerMmHeight: z.string(),
      reason: z.string().nullable(),
      effectiveFrom: z.date(),
      createdBy: z.string().nullable(),
      createdAt: z.date(),
    })
  ),
});

/**
 * Cost breakdown output schema - raw database format
 */
export const costBreakdownOutput = z.object({
  id: z.string(),
  modelId: z.string(),
  component: z.string(),
  costType: z.enum(["fixed", "per_mm_width", "per_mm_height", "per_sqm"]),
  unitCost: z.string(),
  notes: z.string().nullable(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

/**
 * List models output schema
 */
export const listModelsOutput = z.object({
  items: z.array(modelOutput),
  total: z.number().int(),
  totalPages: z.number().int(),
});

/**
 * Delete success output schema
 */
export const deleteSuccessOutput = z.object({
  success: z.literal(true),
});

// ============================================================================
// TYPE EXPORTS (for TypeScript)
// ============================================================================

export type ListModelsInput = z.infer<typeof listModelsInput>;
export type GetModelByIdInput = z.infer<typeof getModelByIdInput>;
export type CreateModelInput = z.infer<typeof createModelInput>;
export type UpdateModelInput = z.infer<typeof updateModelInput>;
export type DeleteModelInput = z.infer<typeof deleteModelInput>;
export type AddCostBreakdownInput = z.infer<typeof addCostBreakdownInput>;
export type UpdateCostBreakdownInput = z.infer<typeof updateCostBreakdownInput>;
export type DeleteCostBreakdownInput = z.infer<typeof deleteCostBreakdownInput>;

export type ModelOutput = z.infer<typeof modelOutput>;
export type ModelDetailOutput = z.infer<typeof modelDetailOutput>;
export type ListModelsOutput = z.infer<typeof listModelsOutput>;
export type CostBreakdownOutput = z.infer<typeof costBreakdownOutput>;
